language: ruby
cache: bundler
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8db2466adb9dde00c41e
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
rvm:
  - 2.1.1

bundler_args: --without integration development
before_script:
#  - bundle exec berks
script:
#  - bundle exec foodcritic -f any . --tags ~FC007 --tags ~FC015 --tags ~FC023
  - bundle exec rubocop
#  - bundle exec rspec spec/

